---

# roles/bdr_destroy/tasks/main.yml
#
# Nuke running BDR installations from low orbit

- include: bdr_db_stop.yml

- name: Delete data directories
  shell: rm -rf "{{base_data_dir}}/BDR{{item}}/"
  with_items:
    - "{{bdr_ports}}"

