---

# bdr_db_stop.yml

- name: Check pidfiles
  stat: path="{{base_data_dir}}/BDR{{item}}/postmaster.pid"
  register: pidfile_check
  with_items:
    - "{{bdr_ports}}"

- name: Stop servers
  shell: "{{bdr_bin}}/pg_ctl -D {{base_data_dir}}/BDR{{item.item}} -m fast -w stop"
  when: item.stat.exists
  with_items:
    - "{{pidfile_check.results}}"
