---

# udr_db_stop.yml

- name: Check pidfiles
  stat: path="{{base_data_dir}}/UDR{{item}}/postmaster.pid"
  register: pidfile_check
  with_items:
    - "{{udr_ports}}"

- name: Stop servers
  shell: "{{udr_bin}}/pg_ctl -D {{base_data_dir}}/UDR{{item.item}} -m fast -w stop"
  when: item.stat.exists
  with_items:
    - "{{pidfile_check.results}}"

